version: 2
before:
  hooks:
    - go mod download
builds:
  - id: bpasswd
    main: ./main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s -X main.version={{.Version}}
    goarch:
      - "386"
    goos:
      - linux
    binary: "bpasswd_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
archives:
  - format: binary
    name_template: "{{ .Binary }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
checksum:
  disable: true
upx:
  - enabled: true
    compress: best
    lzma: true
    brute: true
release:
  prerelease: auto